apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  # JSON patch
  - target:
      kind: Namespace
      name: perf-rhtap-tenant
    patch: |-
      - op: replace
        path: /metadata/name
        value: test-rhtap-1004-tenant
  - target:
      kind: RoleBinding
      name: perf-rhtap-tenant-konflux-admins
    patch: |-
      - op: replace
        path: /metadata/name
        value: test-rhtap-1004-tenant-konflux-admins
      - op: add
        path: /metadata/namespace
        value: test-rhtap-1004-tenant
  - target:
      kind: LimitRange
      name: perf-rhtap-tenant-resource-limits
    patch: |-
      - op: replace
        path: /metadata/name
        value: test-rhtap-1004-tenant-resource-limits
      - op: add
        path: /metadata/namespace
        value: test-rhtap-1004-tenant
  - target:
      kind: ResourceQuota
      name: perf-rhtap-tenant-resource-quota
    patch: |-
      - op: replace
        path: /metadata/name
        value: test-rhtap-1004-tenant-resource-quota
      - op: add
        path: /metadata/namespace
        value: test-rhtap-1004-tenant

resources:
  - ../../base
