---
# Integer; Required; Used as a starting point/number in the range
starts_from:

# Integer; Required; Used as a ending point/number in the range
ends_at:

# Prefix used when generating GitHub repository names
repository_name_prefix: "test-rhtap-tenant-repo-"

# Prefix used when generating Konflux application names
application_name_prefix: "test-rhtap-tenant-app-"

# Prefix used when generating Konflux component names
component_name_prefix: "test-rhtap-tenant-comp-"

# Test scenarios [rok - RHEL on Konflux and Fedora on Konflux | fkx - Fedora on Konflux]
test_scenario:

# fkx tenant workspace
fedora_tenant_namespace: 'konflux-fedora-perfscale-tenant'

# rok tenant workspace(s) prefix
rok_tenant_namespace_prefix: 'test-rhtap-'

# rok tenant workspace(s) suffic
rok_tenant_namespace_suffix: '-tenant'

# Run RPM build with multiple architectures
build_multi_arch: false

# RPM package source in GitHub
distgit_rpm_package_source: "git@github.com:mcharanrm/example-fedora-konflux-libecpg-perf-fork.git"

# Temporary workspace/directory for generating build pipelines, committing it and creating pull requests
git_workspace_dir: "build-pipelines-workspace"

# Path to read GitHub PATs
github_pat_file: "{{ ansible_facts['user_dir'] + '/.github-pat.json' }}"

# Configuration for interacting with the GitHub API
github_api:
  base_url: "https://api.github.com"
  # Endpoint for accessing GitHub repositories
  get_repository:
    path: /repos/mcharanrm
    method: GET
    expected_status: 200

  # Endpoint for creating GitHub repositories
  create_repository:
    path: "/user/repos"
    method: "POST"
    expected_status: 201  

  # Endpoint for deleting GitHub repositories
  delete_repository:
    path: "/repos/mcharanrm"
    method: "DELETE"
    expected_status: 204

  # Endpoint for adding/removing a repository to a GitHub App installation
  kflux_gh_app:
    installation:
      path:  "/user/installations/88047488/repositories"
      quay_org: "redhat-user-workloads-stage"
    add:
      method: "PUT"
      expected_status: 204
    remove:
      method: "PUT"
      expected_status: 204
    # konflux_staging:
    #   path: "/user/installations/88047488/repositories"
    #   quay_org: "redhat-user-workloads-stage"
    # konflux_fedora:
    #   path:  "/user/installations/89145558/repositories"
    #   quay_org: "konflux-fedora"
    # redhat_konflux:
    #   path: "/user/installations/88048036/repositories"
    #   quay_org: "redhat-user-workloads"

  # Endpoint for creating GitHub Pull Requests
  create_pull_request:
    path: "/repos/mcharanrm"
    method: "POST"
    expected_status: 201

  # Number of retry attempts
  retries: 60

  # Delay (in seconds) between retry attempts
  delay_seconds: 60
