apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  # JSON patch
  - target:
      kind: Application 
      name: app
    patch: |-
      - op: replace
        path: /metadata/name
        value: test-rhtap-tenant-app-758 
      - op: replace
        path: /metadata/namespace
        value: test-rhtap-758-tenant
      - op: replace 
        path: /spec/displayName
        value: test-rhtap-tenant-app-758
  - target:
      kind: Component
      name: comp
    patch: |-
      - op: replace
        path: /metadata/name
        value: test-rhtap-tenant-comp-758      
      - op: replace
        path: /metadata/namespace
        value: test-rhtap-758-tenant
      - op: replace
        path: /spec/application
        value: test-rhtap-tenant-app-758
      - op: replace
        path: /spec/componentName
        value: test-rhtap-tenant-comp-758
      - op: replace
        path: /spec/source/git/url
        value: https://github.com/mcharanrm/test-rhtap-tenant-repo-758.git

resources:
  - ../../../../create-konflux-manifests/base
  - konflux-perf-scale-release-plan.yaml
